site_name: teamtomo/ttmask
site_url: https://teamtomo.org/ttmask
site_author: teamtomo
site_description: >-
  Documentation for ttmask
repo_name: teamtomo/ttmask
repo_url: https://github.com/teamtomo/ttmask
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2022 - 2022 teamtomo


# Custom navigation can be specified
nav:
  - Overview: overview.md
  - Examples:

      - Cone: examples/cone.md
      - Cube: examples/cube.md
      - Cuboid: examples/cuboid.md
      - Cylinder: examples/cylinder.md
      - Ellipsoid: examples/ellipsoid.md
      - Sphere: examples/sphere.md
theme:
  icon:
    logo: material/cube-outline
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue

  features:
    - navigation.instant
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.tabs.link

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocs-video